server:
  port: 8082 # 项目启动的端口

spring:
  profiles:
    active: dev # 默认激活 dev 本地开发环境

# log-impl: 设置 MyBatis 的日志实现。org.apache.ibatis.logging.stdout.StdOutImpl 表示将日志输出到标准输出（控制台）。其他可选的日志实现包括：
# org.apache.ibatis.logging.slf4j.Slf4jImpl：使用 SLF4J
# org.apache.ibatis.logging.log4j.Log4jImpl：使用 Log4j
# org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl：使用 Jakarta Commons Logging
# map-underscore-to-camel-case: 设置是否自动将数据库中的下划线命名转换为驼峰命名。例如，数据库中的 user_name 字段将自动映射到 Java 对象中的 userName 属性
mybatis:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 阿里云
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-web-simon

rate-limit:
  api:
    limit: 100

